The3mpire/Ricochet

Ricochet/Assets/_Prefabs/Interactables/Ball.prefab
Ricochet/Assets/_Prefabs/Player.prefab
Ricochet/Assets/_Scripts/DontGoThroughThings.cs
Ricochet/Assets/_Scripts/DontGoThroughThings.cs.meta

Added the DontGoThroughThings script, and adjusted it to fit code conventions (sans variable tooltips because I don't know what they do yet)
Added the DontGoThroughThings script to the ball and player prefabs.
Changed collision detection on player and ball prefab RigidBoy2Ds to Continuous. If the script doesn't fix the collision issues, this will hopefully help.

Stop Collision Ignoring

---

Ricochet/Assets/_Scripts/Player/PlayerController.cs

Replaced Unity input manager usages with Rewired input

Fixed input bug

---

Ricochet/Assets/_Scripts/Modes/Ball.cs

Gave the ball the ability to switch between linear and inverse-square slowing curves using the "Curve Slow" checkbox in the Inspector. The ball's slow speed when using Curve Slow can be adjusted using the Curve Modifier value so the Slow Rate value doesn't have to be changed (thus messing with the linear slow rate).

Added velocity curve option

---

Ricochet/Assets/_Prefabs/Player.prefab

I changed the main bean prefab collider and made it smaller. That is the only change I made.

Changed the prefab hit boxes. Made them smaller.

---

Ricochet/Assets/_Scripts/Managers/EndGameSceneManager.cs
Ricochet/Assets/_Scripts/Managers/GameManager.cs
Ricochet/Assets/_Scripts/Player/PlayerController.cs

Set up default values to allow for easier debugging/development.

Set up default values to be used when developing scenes.

---

Ricochet/Assets/_Art/2D Sprites/Environment/Backgrounds/background.png.meta
Ricochet/Assets/_Prefabs/LevelBuilding/Rewired Input Manager.prefab
Ricochet/Assets/_Scenes/RoyLevels/DiagonalAlley.unity
Ricochet/Assets/_Scenes/TransitionScenes/EndGame.unity
Ricochet/Assets/_Scripts/CharacterSelectScripts/CharSelectManager.cs
Ricochet/Assets/_Scripts/CharacterSelectScripts/CharSelect_PlayerController.cs
Ricochet/Assets/_Scripts/Managers/GameManager.cs
Ricochet/Assets/_Scripts/Managers/LevelSelectManager.cs

Finished fixing win team text on End Game scene. Added return to previous screen functionality to Character and Level select scenes.

Fix win team

---

Ricochet/Assets/_Scenes/RoyLevels/DiagonalAlley.unity
Ricochet/Assets/_Scenes/RoyLevels/Elevator.unity
Ricochet/Assets/_Scenes/RoyLevels/UpNOver.unity
Ricochet/Assets/_Scripts/CharacterSelectScripts/CharSelectManager.cs
Ricochet/Assets/_Scripts/Managers/EndGameSceneManager.cs
Ricochet/Assets/_Scripts/Managers/GameManager.cs
Ricochet/Assets/_Scripts/Managers/ScoreManager.cs
Ricochet/ProjectSettings/EditorBuildSettings.asset

Implemented winner decision based on match time ending.

Timer game winner

---

Ricochet/Assets/_Scripts/GameData.cs
Ricochet/Assets/_Scripts/Managers/EndGameSceneManager.cs
Ricochet/Assets/_Scripts/Managers/GameManager.cs

Fixed missing bracket

---

Ricochet/Assets/_Scripts/CharacterSelectScripts/CharSelect_Assign.cs
Ricochet/Assets/_Scripts/Managers/GameManager.cs

Put in a UI check for the GameManager

Removed a Debug

---

Ricochet/Assets/_Prefabs/Character/Base Player With Particles.prefab
Ricochet/Assets/_Scenes/Art Showcase.unity
Ricochet/Assets/_Scenes/RoyLevels/DiagonalAlley.unity
Ricochet/Assets/_Scenes/TransitionScenes/MainMenu.unity
Ricochet/Assets/_Scripts/Managers/GameManager.cs

Also contains fix for Main Menu scene file

Diagonal alley art

---

Ricochet/Assets/_Scripts/CharacterSelectScripts/CharSelectManager.cs

Char. Select was calling load scene many times, now it only does it once.

Bug Fix - Transition formo char select to level select

---

Ricochet/Assets/Resources/_Art/Chris C Particle Effects/Materials/Glow Smoke MAT.mat
Ricochet/Assets/Resources/_Art/Chris C Particle Effects/Materials/Glow Smoke MAT.mat.meta
Ricochet/Assets/Resources/_Art/Chris C Particle Effects/Materials/spark MAT.mat
Ricochet/Assets/Resources/_Art/Chris C Particle Effects/Materials/spark MAT.mat.meta
Ricochet/Assets/Resources/_Art/Chris C Particle Effects/Particles Systems/Glowing Bar (1).prefab
Ricochet/Assets/Resources/_Art/Chris C Particle Effects/Particles Systems/Glowing Bar (1).prefab.meta
Ricochet/Assets/_Prefabs/LevelBuilding/Goal Blue.prefab
Ricochet/Assets/_Prefabs/LevelBuilding/Goal Red.prefab

Updated goal prefabs to use new goal particle

Added goal particle

---

Ricochet/Assets/_Scenes/TransitionScenes/CharacterSelect.unity
Ricochet/Assets/_Scripts/CharacterSelectScripts/CharSelectManager.cs

Change Circles to Squares,
Fix Undo Ready Bug

Fix Char Select Cancel All Ready Bug

---

Ricochet/Assets/_Scenes/KyleDev.unity
Ricochet/Assets/_Scenes/KyleDev.unity.meta
Ricochet/Assets/_Scripts/Managers/GameManager.cs
Ricochet/Assets/_Scripts/Managers/PowerUpManager.cs
Ricochet/Assets/_Scripts/PowerUp.cs

Fixed issues with multiball. Changed scale of spawned balls. Added settings for max number and number to spawn.

Multi ball powerup

---

Ricochet/Assets/_Prefabs/Character/Player.prefab

Movement Settings: Set lateral Acceleration to .5, Thruster Speed to 25, Direction Switch Ratio to .5. 
For Dash Settings: Dash Speed to 50, and Dash cost to 3. The player now gets around 5 dashes to start.

New Dash settings/Controls

---

Ricochet/Assets/_Scripts/Managers/LevelSelectManager.cs

fixed a bug where trying to go back from level select would send you to a level instead

scene sequence bug fix

---

Ricochet/Assets/Resources/_Art/Animations/Computer Controller.controller

Added isDead bool to trigger death animation. Redid transitions to death state.

Fixed Computer animation controller

---

Ricochet/Assets/_Prefabs/LevelBuilding/Goal Blue Angled.prefab
Ricochet/Assets/_Prefabs/LevelBuilding/Goal Blue.prefab
Ricochet/Assets/_Prefabs/LevelBuilding/Goal Red Angled.prefab
Ricochet/Assets/_Prefabs/LevelBuilding/Goal Red.prefab
Ricochet/Assets/_Scenes/RoyLevels/DiagonalAlley.unity

Resized both goals to 1.3 from 1.

Larger goals on Diagonal Alley

---

Ricochet/Assets/_Prefabs/Required Scene Components.prefab
Ricochet/Assets/_Scripts/Camera/MultipleTargetsCamera.cs
Ricochet/Assets/_Scripts/Managers/GameManager.cs
Ricochet/Assets/_Scripts/Managers/PauseMenuManager.cs
Ricochet/Assets/_Scripts/Player/PlayerController.cs

See specific bugs in the commit messages

Some sprint 9 bug fixes

---

Ricochet/Assets/_Scenes/OfficialLevels/DiagonalAlley_Taller.unity
Ricochet/Assets/_Scenes/OfficialLevels/ElevTaller2.unity
Ricochet/Assets/_Scenes/OfficialLevels/EmptyLevel.unity
Ricochet/Assets/_Scenes/OfficialLevels/UpNOver_Wider.unity

GOOD BY SWEET FREEZE WE HARDLY NEED THEE
Shouldn't be anything that raises any eyebrows. Good luck!

Removed freezee from all power up spawns. 

---

Ricochet/Assets/_Scenes/TransitionScenes/Level Select.unity

Putt static in the back and cleaned up the sliders.

Altered level select to be more consisitent with the start screen.

---

Ricochet/Assets/_Scenes/OfficialLevels/EmptyLevel.unity

Pushed back both goals. Made changes to the left and right wall-Edited the wall collider, added an edge collider on both sides of the goals, and pushed back the kill zone. The edge colliders were added to the wall sprites and I put friction less material on them.

empty level changes to the goal position

---

Ricochet/Assets/_Scenes/OfficialLevels/UpNOver_Wider.unity

Sorry for the new pull request but Geoff wanted the power ups HIGHER

Edited the respawn locations of the power ups and player respawn

---

Ricochet/Assets/_Scenes/TransitionScenes/Level Select.unity

Fixed Level Select to work with other aspect ratios and updated confirm menu look.

Level Select aspect ratio fix

---

Ricochet/Assets/Xbox Live/GameSave/GameSave.unitypackage.meta
Ricochet/Assets/Xbox Live/Tools/AssociationWizard/AssociationWizard.pdb.meta
Ricochet/Assets/_ScriptableObjects/GameData.asset
Ricochet/ProjectSettings/ProjectSettings.asset
Ricochet/ProjectSettings/QualitySettings.asset

Last pull request to update the project settings

Project settings update

---

Ricochet/Assets/_Art/Chris C Particle Effects/Particles Systems/Freeze Effect.prefab
Ricochet/Assets/_Art/Chris C Particle Effects/Particles Systems/Freeze Powerup Orb.prefab
Ricochet/Assets/_Scripts/Player/PlayerController.cs

Use the Arrow Keys to aim the shield in the desired direction

Fix keyboard shield controls
